<?php

namespace OC\BrokersBundle\Repository;

/**
 * BrokersOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokersOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
