<?php

namespace OC\BrokersBundle\Repository;

/**
 * BrokersArrayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokersArrayRepository extends \Doctrine\ORM\EntityRepository
{
}
