<?php

namespace OC\BrokersBundle\Repository;

/**
 * BrokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrokerRepository extends \Doctrine\ORM\EntityRepository
{
}
