services:
    oc_platform.antispam:
        class: OC\PlatformBundle\Antispam\OCAntispam

    oc_platform.websocket:
        class: OC\PlatformBundle\Websocket\OCWebsocket

#    oc_platform.example:
#        class: OC\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
