OC\BrokersBundle\Entity\BrokerPays:
    type: entity
    table: broker_pays
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: _id
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        logo:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        review:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        link:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        score:
            type: integer
            nullable: true
            options:
                unsigned: false
        crypto:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
        displayName:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: display_name
        parent:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
    lifecycleCallbacks: {  }
