OC\BrokersBundle\Entity\BrokersOrder:
    type: entity
    table: brokers_order
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        brokerId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: broker_id
    lifecycleCallbacks: {  }
