OC\BrokersBundle\Entity\OcAdvert:
    type: entity
    table: oc_advert
    uniqueConstraints:
        UNIQ_B1931753DA5256D:
            columns:
                - image_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: false
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        author:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: 0
            options:
                fixed: false
        published:
            type: boolean
            nullable: false
    manyToOne:
        image:
            targetEntity: OcImage
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
